# Claim Analyzer Agent Configuration for MCP Server

# Database configuration
database:
  neo4j:
    uri: "bolt://localhost:7687"
    user: "neo4j"
    password: "password"
    max_pool_size: 20
    connection_timeout: 30
    
  qdrant:
    host: "localhost"
    port: 6333
    timeout: 30
    collection_prefix: "claim_analyzer_"
    
  redis:
    url: "redis://localhost:6379"
    max_connections: 50
    cache_ttl: 3600  # 1 hour

# Agent-specific settings
agent:
  name: "claim_analyzer"
  version: "1.0.0"
  
  # Processing settings
  max_results: 10
  confidence_threshold: 0.5
  batch_size: 50
  processing_interval: 300  # 5 minutes
  
  # Claim extraction settings
  min_claim_length: 10
  max_claim_length: 1000
  claim_confidence_threshold: 0.3
  
  # Fact-checking settings
  similarity_threshold: 0.7
  evidence_limit: 15
  cross_domain_analysis: true
  
  # Performance settings
  max_concurrent_checks: 5
  rate_limit_delay: 2.0
  enable_caching: true

# NLP and ML models
models:
  spacy_model: "en_core_web_sm"
  sentence_transformer: "all-MiniLM-L6-v2"
  
  # Model-specific settings
  embedding_dimensions: 384
  batch_size: 32
  device: "cpu"  # or "cuda" for GPU

# Source credibility scoring
source_credibility:
  # Fact-checking sites
  "snopes.com": 0.95
  "factcheck.org": 0.95
  "politifact.com": 0.90
  "fullfact.org": 0.90
  
  # News organizations
  "reuters.com": 0.90
  "bbc.com": 0.85
  "npr.org": 0.85
  "ap.org": 0.90
  
  # Government/Official sources
  "nasa.gov": 0.95
  "cdc.gov": 0.95
  "who.int": 0.90
  "nih.gov": 0.90
  "noaa.gov": 0.90
  
  # Academic/Research
  "wikipedia.org": 0.80
  "nature.com": 0.95
  "science.org": 0.95
  "arxiv.org": 0.80
  "pubmed.ncbi.nlm.nih.gov": 0.90
  
  # Default scores by domain
  default_credibility:
    government: 0.85
    academic: 0.80
    news: 0.70
    blog: 0.40
    social_media: 0.20
    unknown: 0.50

# Domain classification keywords
domain_keywords:
  science:
    - "experiment"
    - "study" 
    - "research"
    - "theory"
    - "hypothesis"
    - "data"
    - "evidence"
    - "scientific"
    - "empirical"
    - "methodology"
    
  math:
    - "theorem"
    - "proof"
    - "equation"
    - "formula"
    - "calculate"
    - "number"
    - "geometry"
    - "algebra"
    - "statistics"
    - "mathematical"
    
  religion:
    - "god"
    - "faith"
    - "belief"
    - "scripture"
    - "church"
    - "prayer"
    - "divine"
    - "spiritual"
    - "holy"
    - "sacred"
    
  history:
    - "ancient"
    - "war"
    - "civilization"
    - "empire"
    - "century"
    - "historical"
    - "period"
    - "dynasty"
    - "archaeological"
    - "medieval"
    
  literature:
    - "novel"
    - "poem"
    - "author"
    - "book"
    - "story"
    - "character"
    - "literary"
    - "narrative"
    - "fiction"
    - "poetry"
    
  philosophy:
    - "ethics"
    - "logic"
    - "metaphysics"
    - "epistemology"
    - "moral"
    - "existence"
    - "philosophical"
    - "ontology"
    - "phenomenology"
    - "existential"

# Claim detection patterns (regex)
claim_patterns:
  factual_statements:
    - "(?:is|are|was|were|will be|has been|have been)\\s+(?:a|an|the)?\\s*\\w+"
    - "(?:claims?|states?|argues?|believes?|says?)\\s+that\\s+.*"
    - "(?:according to|research shows|studies indicate|experts say)\\s+.*"
    - "(?:it is|this is|that is)\\s+(?:true|false|correct|incorrect|a fact)\\s+that\\s+.*"
    
  absolute_statements:
    - "\\b(?:always|never|all|none|every|no one|everyone)\\b"
    - "\\b(?:completely|totally|absolutely|entirely|wholly)\\b"
    
  statistical_claims:
    - "\\d+\\s*(?:percent|%|out of|in \\d+)"
    - "\\b(?:majority|minority|most|few|many|several)\\b"
    
  temporal_claims:
    - "\\b(?:since|until|before|after|during|while)\\b.*\\b(?:year|century|decade|era)\\b"
    - "\\b(?:first|last|earliest|latest|recent|ancient)\\b"

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "agents/analytics/claim_analyzer/logs/claim_analyzer.log"
  max_size: "100MB"
  backup_count: 5
  
  # Component-specific logging
  components:
    claim_extractor: "INFO"
    fact_checker: "INFO"
    database: "WARNING"
    models: "WARNING"

# Security settings
security:
  input_validation:
    max_text_length: 100000
    sanitize_html: true
    filter_malicious_patterns: true
    
  rate_limiting:
    max_requests_per_minute: 60
    max_claims_per_request: 10
    burst_limit: 5
    
  data_privacy:
    anonymize_sources: false
    retention_period_days: 365
    encrypt_sensitive_data: false

# Performance optimization
performance:
  # Caching strategies
  caching:
    enable_claim_cache: true
    enable_evidence_cache: true
    enable_similarity_cache: true
    cache_size_limit: "1GB"
    
  # Parallel processing
  parallel_processing:
    max_workers: 4
    chunk_size: 25
    enable_async: true
    
  # Database optimization
  database_optimization:
    connection_pooling: true
    query_timeout: 30
    batch_operations: true
    index_optimization: true

# Feature flags
features:
  # Core features
  claim_extraction: true
  fact_checking: true
  similarity_search: true
  cross_domain_analysis: true
  
  # Advanced features
  real_time_processing: true
  automated_verification: true
  sentiment_analysis: false
  bias_detection: false
  multimodal_analysis: false
  
  # Experimental features
  llm_integration: false
  automated_learning: false
  community_validation: false
  blockchain_verification: false