# Analysis Pipeline Configuration
# Configuration for AI agent analysis pipelines and workflows

pipeline:
  agents:
    text_processor:
      enabled: true
      priority: 1
      timeout: 120  # seconds
      parameters:
        chunk_size: 1000
        overlap: 200
        language_detection: true
        entity_extraction: true
        sentiment_analysis: true
        
    claim_analyzer:
      enabled: true
      priority: 2
      timeout: 180  # seconds
      parameters:
        confidence_threshold: 0.7
        fact_check_sources: ["wikipedia", "scholarly_sources"]
        cross_reference: true
        bias_detection: true
        
    concept_explorer:
      enabled: true
      priority: 3
      timeout: 240  # seconds
      parameters:
        relationship_threshold: 0.6
        max_concepts: 100
        cross_domain_analysis: true
        hypothesis_generation: true
        
    vector_indexer:
      enabled: true
      priority: 4
      timeout: 60   # seconds
      parameters:
        embedding_model: "all-MiniLM-L6-v2"
        batch_size: 32
        normalize_embeddings: true
        
  execution:
    default_mode: "sequential"  # sequential, parallel, hybrid
    max_concurrent_agents: 3
    pipeline_timeout: 600       # seconds (10 minutes)
    retry_failed_agents: true
    max_retries: 2
    
  quality_control:
    confidence_threshold: 0.6
    consistency_check: true
    cross_validation: true
    human_review_threshold: 0.4
    
  workflows:
    quick_analysis:
      agents: ["text_processor", "vector_indexer"]
      mode: "parallel"
      timeout: 180
      
    comprehensive_analysis:
      agents: ["text_processor", "claim_analyzer", "concept_explorer", "vector_indexer"]
      mode: "sequential"
      timeout: 600
      
    fact_checking:
      agents: ["text_processor", "claim_analyzer"]
      mode: "sequential"
      timeout: 300
      
    concept_discovery:
      agents: ["text_processor", "concept_explorer", "vector_indexer"]
      mode: "hybrid"
      timeout: 400
      
domains:
  mathematics:
    specialized_agents: ["concept_explorer", "claim_analyzer"]
    confidence_boost: 0.1
    domain_keywords: ["theorem", "proof", "equation", "formula", "axiom"]
    
  science:
    specialized_agents: ["claim_analyzer", "vector_indexer"]
    confidence_boost: 0.1
    domain_keywords: ["hypothesis", "experiment", "theory", "data", "research"]
    
  philosophy:
    specialized_agents: ["concept_explorer", "text_processor"]
    confidence_boost: 0.1
    domain_keywords: ["ethics", "metaphysics", "logic", "consciousness", "reality"]
    
  art:
    specialized_agents: ["text_processor", "concept_explorer"]
    confidence_boost: 0.05
    domain_keywords: ["aesthetic", "beauty", "creative", "artistic", "cultural"]
    
  language:
    specialized_agents: ["text_processor", "vector_indexer"]
    confidence_boost: 0.1
    domain_keywords: ["linguistic", "grammar", "syntax", "semantic", "phonetic"]
    
  technology:
    specialized_agents: ["claim_analyzer", "concept_explorer"]
    confidence_boost: 0.1
    domain_keywords: ["innovation", "engineering", "invention", "mechanism", "system"]

processing:
  batch:
    enabled: true
    size: 10
    parallel_batches: 3
    
  priority:
    high: 
      timeout: 300
      max_agents: 5
    medium:
      timeout: 600
      max_agents: 4
    low:
      timeout: 900
      max_agents: 3
      
  results:
    format: "json"
    include_metadata: true
    include_confidence_scores: true
    include_processing_stats: true
    
monitoring:
  metrics:
    track_processing_time: true
    track_success_rate: true
    track_confidence_scores: true
    track_agent_performance: true
    
  alerts:
    high_failure_rate: 0.2      # 20%
    slow_processing: 300        # seconds
    low_confidence: 0.3         # 30%
    queue_backup: 50            # items
    
  reporting:
    daily_summary: true
    weekly_analysis: true
    performance_trends: true
    
optimization:
  auto_tune: true
  learning_rate: 0.1
  adaptation_threshold: 0.8
  
  agent_selection:
    dynamic: true
    performance_based: true
    domain_aware: true
    
  resource_management:
    cpu_threshold: 80     # percent
    memory_threshold: 80  # percent
    disk_threshold: 90    # percent