# Database Agents Configuration
# Configuration for Neo4j, Qdrant, and Database Sync Manager

neo4j_agent:
  connection:
    uri: "bolt://localhost:7687"
    user: "neo4j"
    password: "${NEO4J_PASSWORD}"
    encrypted: false
    trust: "TRUST_ALL_CERTIFICATES"
    
  performance:
    max_pool_size: 50
    connection_timeout: 30  # seconds
    max_retry_time: 300     # seconds
    initial_retry_delay: 1  # seconds
    retry_delay_multiplier: 2.0
    
  operations:
    batch_size: 1000
    transaction_timeout: 300  # seconds
    max_concurrent_transactions: 10
    
  schema:
    auto_create_indices: true
    enforce_constraints: true
    optimize_queries: true
    
  monitoring:
    log_queries: false
    log_slow_queries: true
    slow_query_threshold: 5000  # milliseconds
    
qdrant_agent:
  connection:
    host: "localhost"
    port: 6333
    timeout: 30
    retries: 3
    api_key: "${QDRANT_API_KEY}"
    
  collections:
    auto_create: true
    optimization_threshold: 10000
    vector_size: 384
    distance_metric: "Cosine"
    
    # Domain-specific collections
    domains:
      documents_mathematics:
        vector_size: 384
        distance: "Cosine"
        hnsw_config:
          m: 16
          ef_construct: 200
      documents_science:
        vector_size: 384
        distance: "Cosine"
        hnsw_config:
          m: 16
          ef_construct: 200
      documents_philosophy:
        vector_size: 384
        distance: "Cosine"
        hnsw_config:
          m: 16
          ef_construct: 200
      documents_art:
        vector_size: 384
        distance: "Cosine"
        hnsw_config:
          m: 16
          ef_construct: 200
      documents_language:
        vector_size: 384
        distance: "Cosine"
        hnsw_config:
          m: 16
          ef_construct: 200
      documents_technology:
        vector_size: 384
        distance: "Cosine"
        hnsw_config:
          m: 16
          ef_construct: 200
      entities:
        vector_size: 384
        distance: "Cosine"
      concepts:
        vector_size: 384
        distance: "Cosine"
      claims:
        vector_size: 384
        distance: "Cosine"
        
  performance:
    batch_size: 100
    max_concurrent_requests: 10
    indexing_threshold: 10000
    
  search:
    default_limit: 10
    max_limit: 1000
    score_threshold: 0.7
    
sync_manager:
  strategy: "event_driven"
  
  intervals:
    consistency_check: 300  # seconds (5 minutes)
    health_check: 60       # seconds
    cleanup: 3600          # seconds (1 hour)
    
  retries:
    max_retry_attempts: 3
    retry_delay: 5         # seconds
    exponential_backoff: true
    
  conflict_resolution:
    strategy: "timestamp"  # timestamp, neo4j_priority, qdrant_priority, manual
    manual_review_threshold: 0.5
    
  consistency:
    tolerance: 0.05        # 5% difference allowed
    deep_check_interval: 86400  # seconds (daily)
    
  events:
    queue_size: 10000
    batch_processing: true
    batch_size: 100
    
  performance:
    max_sync_operations: 1000
    sync_timeout: 120      # seconds
    parallel_operations: 5
    
  monitoring:
    log_all_operations: false
    log_errors: true
    metrics_retention: 30  # days
    
redis_agent:
  connection:
    host: "localhost"
    port: 6379
    db: 0
    password: "${REDIS_PASSWORD}"
    
  performance:
    connection_pool_size: 10
    socket_timeout: 30
    socket_connect_timeout: 30
    
  queues:
    sync_events: "mcp:sync:events"
    processing_queue: "mcp:processing:queue"
    results_queue: "mcp:results:queue"
    
  expiration:
    default_ttl: 3600      # seconds (1 hour)
    long_ttl: 86400        # seconds (1 day)
    cache_ttl: 300         # seconds (5 minutes)