server:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  debug: false

api:
  title: "MCP Knowledge Graph Server"
  description: "Hybrid Neo4j and Qdrant database for knowledge management"
  version: "2.0.0"
  docs_url: "/docs"
  redoc_url: "/redoc"

cors:
  allow_origins: ["*"]
  allow_credentials: true
  allow_methods: ["*"]
  allow_headers: ["*"]

database:
  neo4j:
    uri: "bolt://localhost:7687"
    user: "neo4j"
    password: "password"
    max_pool_size: 20
    connection_timeout: 30
  qdrant:
    host: "localhost"
    port: 6333
    timeout: 30
  redis:
    url: "redis://localhost:6379"
    max_connections: 50

performance:
  cache_type: "hybrid"
  optimization_level: "aggressive"
  batch_sizes:
    document_processing: 25
    graph_updates: 100
    vector_updates: 250

monitoring:
  prometheus_port: 9090
  metrics_enabled: true
  health_check_interval: 30
